framework:
    cache:
        default_redis_provider: 'predis'
        pools:
            app.cache.redis:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_HOST)%'
                default_lifetime: 3600