services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Taxes\:
    resource: '../../src/Taxes/'

  _instanceof:
    App\Taxes\Application\TaxDataProviderInterface:
      tags:
        - { name: tax.tax_provider }

  App\Taxes\Application\TaxDataProviderStrategy:
    arguments:
      $providers: !tagged_iterator { tag: 'tax.tax_provider' }

#  Taxes\UserInterface\Http\GetTaxesAction:
#    arguments:
#      $bus: