<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCgjkRV7\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCgjkRV7/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCgjkRV7.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCgjkRV7\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerCgjkRV7\App_KernelTestDebugContainer([
    'container.build_hash' => 'CgjkRV7',
    'container.build_id' => 'ca5e438a',
    'container.build_time' => 1730897215,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCgjkRV7');
