<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'get_taxes' => [[], ['_controller' => 'Taxes\\UserInterface\\Http\\GetTaxesAction'], [], [['text', '/taxes']], [], [], []],
    'Taxes\UserInterface\Http\GetTaxesAction' => [[], ['_controller' => 'Taxes\\UserInterface\\Http\\GetTaxesAction'], [], [['text', '/taxes']], [], [], []],
    'Taxes\UserInterface\Http\GetTaxesAction::__invoke' => [[], ['_controller' => 'Taxes\\UserInterface\\Http\\GetTaxesAction'], [], [['text', '/taxes']], [], [], []],
];
