<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEPW0lcS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEPW0lcS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEPW0lcS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEPW0lcS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEPW0lcS\App_KernelDevDebugContainer([
    'container.build_hash' => 'EPW0lcS',
    'container.build_id' => 'a81f6c41',
    'container.build_time' => 1731012416,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEPW0lcS');
