<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'get_taxes' => [[], ['_controller' => 'Taxes\\UserInterface\\Http\\GetTaxesAction'], [], [['text', '/taxes']], [], [], []],
    'Taxes\UserInterface\Http\GetTaxesAction' => [[], ['_controller' => 'Taxes\\UserInterface\\Http\\GetTaxesAction'], [], [['text', '/taxes']], [], [], []],
    'Taxes\UserInterface\Http\GetTaxesAction::__invoke' => [[], ['_controller' => 'Taxes\\UserInterface\\Http\\GetTaxesAction'], [], [['text', '/taxes']], [], [], []],
];
